---
name: archer_analysis_preprocessing
pack: gmc_norr
description: Process raw data for loading into Archer Analysis
enabled: true

trigger:
  type: gmc_norr.copy_complete
  parameters:
    config_section: "archer"

action:
  ref: gmc_norr.archer
  parameters:
    run_directory: "{{ trigger.run_directory }}"
