---
name: generate_tumor_evolution_report
pack: gmc_norr_analysis
description: Generate tumor evolution report
enabled: true

trigger:
  type: gmc_norr_analysis.tumor_evolution_request

action:
  ref: gmc_norr_analysis.tumor_evolution
  parameters:
    excel_file: "{{ trigger.excel_file }}"
    sheet: "{{ trigger.sheet }}"
    output_directory: "{{ config_context.tumor_evolution.output_directory }}"
