---
name: scout_annotation
pack: gmc_norr_analysis
description: >
  Move a plumber analysis and update it in Cleve to state ready
  and add output files
enabled: true

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "plumber"

criteria:
  trigger.body.message_type:
    type: equals
    pattern: end
  trigger.body.success:
    type: equals
    pattern: true
  trigger.body.pipeline:
    type: equals
    pattern: genomic-medicine-sweden/Twist_Solid

action:
  ref: scout.annotate_twist_solid
  parameters:
    prev_analysis_id: "{{ trigger.body.analysis_id }}"
    prev_pipeline: "{{ trigger.body.pipeline }}"
    prev_analysis_path: "{{ trigger.body.workdir }}"
