name: start_downstream_analysis
description: Rule for starting analysis for a NovaSeq sequencing run
pack: gmc_norr_analysis
enabled: true

trigger:
  type: cleve.analysis_state_update

criteria:
  trigger.state:
    type: equals
    pattern: ready
  trigger.software:
    type: contains
    pattern: BCLConvert

action:
  ref: gmc_norr_analysis.start_downstream_analysis
  parameters:
    path: "{{ trigger.path }}"
    analysis_id: "{{ trigger.analysis_id }}"
