---
name: webhook_send_notification_email
pack: gmc_norr_analysis
description: >
  Send a notification email for plumber
enabled: true

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "plumber"

criteria:
  trigger.body.message_type:
    type: equals
    pattern: end

action:
  ref: core.inject_trigger
  parameters: 
    trigger_name: gmc_norr_analysis.email_notification 
    payload:
      subject: "{{ trigger.body.pipeline }} in {{ trigger.body.workdir }}"
      message: "{{ trigger.body.message }}.\nSuccess: {{trigger.body.success}}\nError: {{ trigger.body.error }}"
